# Generated by Django 4.1.7 on 2023-03-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shape',
            field=models.CharField(blank=True, choices=[('AMPH', 'Amphora'), ('STJR', 'Stirrup Jar'), ('JG', 'Jug'), ('CUP', 'Cup'), ('RHY', 'Rhyton'), ('FG', 'Figure')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(),
        ),
    ]
