# Generated by Django 4.1.7 on 2023-03-24 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_shape_alter_item_image_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='shape',
            field=models.CharField(blank=True, choices=[('Amphora', 'Amphora'), ('Stirrup_Jar', 'Stirrup Jar'), ('Jug', 'Jug'), ('Cup', 'Cup'), ('Mug', 'Mug'), ('Rhyton', 'Rhyton'), ('Figure', 'Figure'), ('Strainer', 'Strainer'), ('Spouted_Jar', 'Spouted Jar'), ('Ewer', 'Ewer'), ('Flask', 'Flask')], max_length=255, null=True),
        ),
    ]
