# Generated by Django 4.1.7 on 2023-03-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_created_at_alter_item_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, upload_to='media')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
    ]
