# Generated by Django 4.1.7 on 2023-03-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media'),
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
