# Generated by Django 4.1.7 on 2023-03-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiringType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image1', models.ImageField(max_length=255, upload_to='media')),
                ('image2', models.ImageField(max_length=255, upload_to='media')),
                ('image3', models.ImageField(max_length=255, upload_to='media')),
                ('image4', models.ImageField(max_length=255, upload_to='media')),
            ],
        ),
    ]
