# Generated by Django 4.1.7 on 2023-03-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firingtype',
            name='color',
            field=models.CharField(choices=[('gray-100', 'gray-100'), ('white', 'white')], max_length=255, null=True),
        ),
    ]
