# Generated by Django 4.1.7 on 2023-03-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_firingtype_image1_remove_firingtype_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='media')),
                ('partner', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('Experimental', 'Experimental'), ('Seminars', 'Seminars'), ('Theories', 'Theories'), ('Activities', 'Activities'), ('Collaborations', 'Collaborations')], max_length=255)),
            ],
        ),
    ]
