# Generated by Django 4.1.7 on 2023-03-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
