# Generated by Django 4.1.7 on 2023-04-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
