# Generated by Django 4.1.7 on 2023-03-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
